"""empty message

Revision ID: 53944a0dd084
Revises: c3dcab03a625
Create Date: 2026-04-27 04:44:08.618640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53944a0dd084'
down_revision = 'c3dcab03a625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
